version: 2
jobs:
  build:
    docker:
      - image: ubuntu:trusty

    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: true
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    steps:
      - checkout
      - run:
          name: Run tests
          command: ./build.sh
