version: 2
jobs:
  build:
    docker:
      - image: ubuntu:trusty

    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: true
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      - TERM: dumb

    working_directory: ~/circleci-entityframework

    steps:
      - run:
          name: Install missing packages
          command: apt update && apt install -y git openssh-client uuid-runtime wget unzip libunwind8-dev libssl-dev libicu-dev
      - checkout
      - run:
          name: Run tests
          command: ./build.sh
