version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk

    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: true
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      - TERM: dumb

    working_directory: ~/circleci-entityframework

    steps:
      - run:
          name: Install missing packages
          command: apt update && apt install -y git openssh-client
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Run tests
          command: dotnet test
